### Login to get a token
# @name login
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "newuser",
  "password": "securepassword"
}

### Get all blogs
GET http://localhost:3003/api/blogs

### Create a new blog without token (Should fail)
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "New Blog Post",
    "author": "Author Name",
    "url": "http://example.com/new-blog-post",
    "likes": 0
}

### Create a new blog with token (run login first to get the token)
# @name createBlog
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
    "title": "New Blog Post",
    "author": "Author Name",
    "url": "http://example.com/new-blog-post",
    "likes": 0
}

### Delete a blog without token (Should fail)
DELETE http://localhost:3003/api/blogs/{{createBlog.response.body.id}}

### Delete a blog with token (run login first to get the token)
DELETE http://localhost:3003/api/blogs/{{createBlog.response.body.id}}
Authorization: Bearer {{login.response.body.token}}