### Get info about the phonebook
GET http://localhost:3001/info

### Get all persons
GET http://localhost:3001/api/persons

### Get a person by ID
GET http://localhost:3001/api/persons/690928344e72c6b226be527b

### Get a person by non-existing ID
GET http://localhost:3001/api/persons/123456789012345678901234

### Get a person by malformatted ID
GET http://localhost:3001/api/persons/12345

### Add a new person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Matti Meikäläinen",
  "number": "12-345678"
}

### Add a person with missing name
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "number": "12-345678"
}

### Add a person with missing number
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Matti Mattinen"
}

### Add a person with name that is too short
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Ma",
  "number": "12-345678"
}

### Add a person with number that is too short
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Matti Meikäläinen",
  "number": "12"
}

### Add a person with invalid number format
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Matti Meikäläinen",
  "number": "1234-432211"
}

### Update a person by ID
PUT http://localhost:3001/api/persons/690b0d2f68b72cc928ebe571
Content-Type: application/json

{
  "name": "REST Tester",
  "number": "12-345678"
}

### Update a person with name that is too short
PUT http://localhost:3001/api/persons/690b0d2f68b72cc928ebe571
Content-Type: application/json

{
  "name": "Ma",
  "number": "12-345678"
}

### Delete a person by ID
DELETE http://localhost:3001/api/persons/690b1d30a04e8b14e5175c92